# Generated by Django 5.0.3 on 2024-03-27 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('GameID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Category', models.CharField(max_length=50)),
                ('Difficulty_Level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('ResourceID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('lesson', 'Lesson'), ('tutorial', 'Tutorial'), ('movie', 'Movie')], max_length=20)),
                ('Description', models.TextField()),
                ('Content', models.CharField(max_length=200)),
                ('Age_Appropriateness', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usersys',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Role', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('ProgressID', models.AutoField(primary_key=True, serialize=False)),
                ('CompletionStatus', models.CharField(max_length=20)),
                ('Grade', models.FloatField()),
                ('TimeSpent', models.IntegerField()),
                ('ResourceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_science_learning_app.learningresource')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_science_learning_app.usersys')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('ReportID', models.AutoField(primary_key=True, serialize=False)),
                ('TasksCompleted', models.IntegerField()),
                ('AverageGrade', models.FloatField()),
                ('AreasForDevelopment', models.TextField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer_science_learning_app.usersys')),
            ],
        ),
    ]
