# Generated by Django 4.2 on 2024-04-10 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('computer_science_learning_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersys',
            name='Password',
        ),
        migrations.AddField(
            model_name='usersys',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='usersys',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usersys',
            name='Role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersys',
            name='Username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='usersys',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
