# Generated by Django 4.2.11 on 2024-04-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computer_science_learning_app", "0003_usersys_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="Image",
            field=models.ImageField(blank=True, null=True, upload_to="game_images/"),
        ),
    ]
