# Generated by Django 4.2.11 on 2024-04-17 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("computer_science_learning_app", "0004_game_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="Image",
            new_name="Imageicon",
        ),
    ]
