# Generated by Django 4.2 on 2024-04-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_science_learning_app', '0005_rename_image_game_imageicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Imageicon',
            field=models.ImageField(blank=True, null=True, upload_to='static/game_images/'),
        ),
    ]
